lib{xxhash}: {h c}{xxhash}

lib{xxhash}: c.export.poptions = "-I$src_base"
c.poptions += "-I$src_base"

if ($c.target.class == 'windows')
{
    {hbmis objs}{*}: c.poptions += "-DXXH_PUBLIC_API=__declspec(dllexport)"
    libs{xxhash}: c.export.poptions += "-DXXH_PUBLIC_API=__declspec(dllimport)"
}

h{*}:
{
    install = include/
}
