lib{xxhash}: {h c}{xxhash}

lib{xxhash}: c.export.poptions = "-I$src_base"
c.poptions += "-I$src_base"

if ($c.target.class == 'windows')
{
    c.poptions += "-DWIN32"
    lib{xxhash}: c.export.poptions += "-DWIN32"
}

{hbmis objs}{*}: c.poptions += "-DXXH_EXPORT=1"
libs{xxhash}: c.export.poptions += "-DXXH_IMPORT=1"

h{*}:
{
    install = include/
}
