lib{xxhash}: {h c}{xxhash}

lib{xxhash}: c.export.poptions = "-I$src_base"
c.poptions += "-I$src_base"

{hbmis objs}{*}: c.poptions += "-DXXH_EXPORT=1"
libs{xxhash}: c.export.poptions += "-DXXH_IMPORT=1"

h{*}:
{
    install = include/
}
